# Generated by Django 5.2.8 on 2025-11-15 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('slug', models.SlugField(unique=True)),
                ('poster', models.URLField(blank=True)),
                ('fondo', models.URLField(blank=True)),
                ('tipo', models.CharField(choices=[('SERIE', 'Serie'), ('PELICULA', 'Película')], default='SERIE', max_length=10)),
                ('anio', models.PositiveIntegerField(blank=True, null=True)),
                ('edad_recomendada', models.CharField(blank=True, max_length=20)),
                ('es_destacada', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('series', models.ManyToManyField(blank=True, related_name='generos', to='catalogo.serie')),
            ],
            options={
                'verbose_name': 'Género',
                'verbose_name_plural': 'Géneros',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Temporada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('titulo', models.CharField(blank=True, max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temporadas', to='catalogo.serie')),
            ],
            options={
                'ordering': ['numero'],
                'unique_together': {('serie', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='Episodio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('titulo', models.CharField(max_length=200)),
                ('sinopsis', models.TextField(blank=True)),
                ('duracion_minutos', models.PositiveIntegerField(blank=True, null=True)),
                ('thumbnail', models.URLField(blank=True)),
                ('video_url', models.URLField(blank=True)),
                ('temporada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodios', to='catalogo.temporada')),
            ],
            options={
                'ordering': ['numero'],
                'unique_together': {('temporada', 'numero')},
            },
        ),
    ]
